const NOTION_AUTH_TOKEN = process.env.NEXT_PUBLIC_NOTION_AUTH_TOKEN
const PROXY_SERVER_URL = process.env.NEXT_PUBLIC_PROXY_SERVER_URL
const GITHUB_TOKEN = process.env.NEXT_PUBLIC_GITHUB_TOKEN

export { NOTION_AUTH_TOKEN, PROXY_SERVER_URL, GITHUB_TOKEN }
